export enum ErrorCode {
  INPUT_VALIDATION = 'INPUT_VALIDATION',
  PDF_PARSE = 'PDF_PARSE',
  OCR = 'OCR',
  MAPPING = 'MAPPING',
  FILL = 'FILL',
  VALIDATION = 'VALIDATION',
  CONFIG = 'CONFIG',
  PIPELINE = 'PIPELINE',
}
